"use client";

import React, { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import {
  askLegalAI,
  uploadDocument,
  recoverIndex,
  logout,
  submitFeedback,
  getToken,
  getCurrentUser,
  clearToken,
  getLocalItem,
  setLocalItem,
} from "@/lib/api";
import Header from "@/components/Header";
import QueryPanel from "@/components/QueryPanel";
import ResponsePanel from "@/components/ResponsePanel";
import DocumentUpload from "@/components/DocumentUpload";
import ModelSelector from "@/components/ModelSelector";
import HistoryPanel from "@/components/HistoryPanel";


const getApiErrorMessage = (err, fallback) => {
  const detail = err?.response?.data?.detail;
  if (Array.isArray(detail)) return detail.join("; ");
  if (typeof detail === "string" && detail.trim()) return detail;
  return err?.message || fallback;
};

const isDocumentScopedQuery = (text) => {
  const q = (text || "").toLowerCase();
  const hints = [
    "this document",
    "uploaded",
    "the file",
    "in this file",
    "according to document",
    "from this document",
  ];
  return hints.some((h) => q.includes(h));
};

const toStructuredAnalysis = (analysis = {}) => {
  const legalIssues = Array.isArray(analysis.legal_issues)
    ? analysis.legal_issues
    : Array.isArray(analysis.legal_sections)
    ? analysis.legal_sections
    : [];
  const keyArguments = Array.isArray(analysis.key_arguments)
    ? analysis.key_arguments
    : Array.isArray(analysis.key_points)
    ? analysis.key_points
    : [];

  return {
    summary: analysis.summary || "",
    case_type: analysis.case_type || "Unknown",
    court: analysis.court || "Not extracted",
    parties: Array.isArray(analysis.parties) ? analysis.parties : [],
    legal_issues: legalIssues,
    key_arguments: keyArguments,
    risk_level: analysis.risk_level || "Unknown",
    recommended_action:
      analysis.recommended_action || analysis.judgement || analysis.summary || "Not available",
  };
};

export default function LegalAIApp() {
  const router = useRouter();
  const [authChecking, setAuthChecking] = useState(true);
  const [query, setQuery] = useState("");
  const [response, setResponse] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [history, setHistory] = useState([]);
  const [uploadedDocs, setUploadedDocs] = useState([]);

  const [activeTab, setActiveTab] = useState("query");
  const [uploadProgress, setUploadProgress] = useState({});
  const [questionMode, setQuestionMode] = useState("general");
  const [feedbackStatus, setFeedbackStatus] = useState("");

  const responseRef = useRef(null);

  useEffect(() => {
    let isMounted = true;

    const validateAuth = async () => {
      const token = getToken();
      if (!token) {
        router.replace("/login");
        return;
      }

      try {
        await getCurrentUser();
        if (isMounted) setAuthChecking(false);
      } catch {
        clearToken();
        if (isMounted) router.replace("/login");
      }
    };

    const handleUnauthorized = () => {
      router.replace("/login");
    };

    window.addEventListener("unauthorized", handleUnauthorized);
    validateAuth();

    return () => {
      isMounted = false;
      window.removeEventListener("unauthorized", handleUnauthorized);
    };
  }, [router]);

  useEffect(() => {
    if (authChecking) return;
    try {
      const savedHistory = getLocalItem("legalAIHistory");
      if (savedHistory) {
        setHistory(JSON.parse(savedHistory));
      }
    } catch (e) {
      console.warn("LocalStorage access denied or failed:", e);
    }
  }, [authChecking]);

  useEffect(() => {
    try {
      setLocalItem("legalAIHistory", JSON.stringify(history.slice(-50)));
    } catch (e) {
      // Ignore storage errors
    }
  }, [history]);

  useEffect(() => {
    if (response && responseRef.current) {
      setTimeout(() => {
        responseRef.current.scrollIntoView({ behavior: "smooth" });
      }, 100);
    }
  }, [response]);

  const handleAskQuestion = async (e) => {
    e.preventDefault();

    if (!query.trim()) {
      setError("Please enter a legal question");
      return;
    }

    try {
      setLoading(true);
      setError("");
      setResponse(null);

      const forceUploaded = questionMode === "document" || isDocumentScopedQuery(query);

      const result = await askLegalAI({
        question: query,
        use_uploaded_context: uploadedDocs.length > 0 ? forceUploaded : false,
      });

      setResponse({
        ...result,
        asked_question: query,
        autoGenerated: false,
        source: result?.source || "rag",
      });

      const historyEntry = {
        id: Date.now(),
        question: query,
        answer: result.answer,
        confidence: result.confidence,
        timestamp: new Date().toISOString(),
      };

      setHistory((prev) => [historyEntry, ...prev]);
      setQuery("");
    } catch (err) {
      setError(`Failed: ${getApiErrorMessage(err, "Error")}`);
    } finally {
      setLoading(false);
    }
  };

  const handleFileUpload = async (files) => {
    if (!files || files.length === 0) return null;

    try {
      setLoading(true);
      setError("");

      const result = await uploadDocument(files, (progress) => {
        setUploadProgress(progress);
      });

      const processedFiles = result?.summary?.files_processed || [];
      const uploaded = processedFiles.map((file) => ({
        id: Date.now() + Math.random(),
        name: file.filename,
        size: file.size_mb,
        uploadedAt: new Date().toISOString(),
        status: "analyzed",
        chunks: file.chunks,
        fileType: file.file_type,
        analysis: file.analysis,
      }));

      setUploadedDocs((prev) => [...prev, ...uploaded]);
      setQuestionMode("document");
      setUploadProgress({ percent: 100, status: "Document analyzed successfully" });

      return result;
    } catch (err) {
      setError(`Upload failed: ${getApiErrorMessage(err, "Upload error")}`);

      if (err.response?.status >= 500) {
        try {
          await recoverIndex();
        } catch {}
      }

      throw err;
    } finally {
      setLoading(false);
    }
  };

  const handleAnalysisReady = (filesProcessed = []) => {
    if (!Array.isArray(filesProcessed) || filesProcessed.length === 0) return;

    const normalizedFiles = filesProcessed.map((file, idx) => {
      const rawAnalysis = file?.analysis || {};
      return {
        name: file?.filename || file?.name || `uploaded_document_${idx + 1}`,
        analysis: toStructuredAnalysis(rawAnalysis),
        raw_analysis: rawAnalysis,
      };
    });

    const latestFile = normalizedFiles[normalizedFiles.length - 1];
    const latestSummary =
      latestFile?.raw_analysis?.summary ||
      latestFile?.analysis?.summary ||
      latestFile?.analysis?.recommended_action ||
      "Document analyzed successfully.";

    setResponse({
      answer: latestSummary,
      confidence: 0.95,
      source: "uploaded_document",
      autoGenerated: true,
      summary: {
        files_processed: normalizedFiles,
      },
      metadata: {
        upload_batch_files: normalizedFiles.length,
        latest_uploaded_file: latestFile?.name || "uploaded_document",
      },
    });
    setQuestionMode("document");
    setActiveTab("query");
  };

  const loadFromHistory = (entry) => {
    setQuery(entry.question);
    setResponse({
      answer: entry.answer,
      confidence: entry.confidence,
      asked_question: entry.question,
      autoGenerated: false,
    });
    setActiveTab("query");
  };

  const clearHistory = () => {
    if (window.confirm("Clear history?")) setHistory([]);
  };

  const handleLogout = async () => {
    try {
      await logout();
    } finally {
      router.replace("/login");
    }
  };

  const handleSubmitFeedback = async ({ queryId, rating, correction = "", details = "" }) => {
    if (!queryId) {
      throw new Error("Missing query id for feedback");
    }
    await submitFeedback({
      query_id: queryId,
      rating,
      correction,
      details,
    });
    setFeedbackStatus("Feedback saved. Thank you.");
    setTimeout(() => setFeedbackStatus(""), 3500);
  };

  if (authChecking) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
        <p className="text-gray-700 font-medium">Checking authentication...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">


      <Header />

      <div className="container mx-auto px-2 sm:px-4 py-4 sm:py-6 lg:py-8 max-w-6xl">
        <div className="flex gap-1 sm:gap-2 mb-6 sm:mb-8 bg-white rounded-lg shadow-md p-1 flex-wrap sm:flex-nowrap">
          <button 
            onClick={() => setActiveTab("query")} 
            className={`tab flex-1 sm:flex-none ${activeTab === "query" ? "bg-green-100 text-green-700 font-bold" : "text-black"}`}
            title="Ask a legal question"
          >
            Ask
          </button>
          <button 
            onClick={() => setActiveTab("history")} 
            className={`tab flex-1 sm:flex-none ${activeTab === "history" ? "bg-green-100 text-green-700 font-bold" : "text-black"}`}
            title="View query history"
          >
            History
          </button>
          <button 
            onClick={() => setActiveTab("settings")} 
            className={`tab flex-1 sm:flex-none ${activeTab === "settings" ? "bg-green-100 text-green-700 font-bold" : "text-black"}`}
            title="Model settings"
          >
            Settings
          </button>
        </div>

        {error && (
          <div className="mb-4 sm:mb-6 p-3 sm:p-4 bg-red-50 border-l-4 border-red-500 rounded-lg text-red-700 shadow-sm text-sm sm:text-base">{error}</div>
        )}

        {activeTab === "query" && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 lg:gap-8">
            <div className="lg:col-span-2 space-y-3 sm:space-y-4">
              {uploadedDocs.length > 0 && (
                <div className="bg-white rounded-lg shadow p-3 sm:p-4 border border-indigo-100">
                  <p className="label-heading text-indigo-800 mb-2 sm:mb-3">Question Mode</p>
                  <div className="flex gap-2 flex-wrap">
                    <button
                      onClick={() => setQuestionMode("document")}
                      className={`px-2 sm:px-3 py-1 sm:py-2 rounded text-xs sm:text-sm font-semibold transition-colors ${
                        questionMode === "document" ? "bg-indigo-600 text-white" : "bg-gray-100 text-gray-700"
                      }`}
                    >
                      Ask about this document
                    </button>
                    <button
                      onClick={() => setQuestionMode("general")}
                      className={`px-2 sm:px-3 py-1 sm:py-2 rounded text-xs sm:text-sm font-semibold transition-colors ${
                        questionMode === "general" ? "bg-indigo-600 text-white" : "bg-gray-100 text-gray-700"
                      }`}
                    >
                      Ask general legal question
                    </button>
                  </div>
                </div>
              )}

              <QueryPanel
                query={query}
                setQuery={setQuery}
                loading={loading}
                onSubmit={handleAskQuestion}
                uploadedDocs={uploadedDocs}
              />

              {response && (
                <div ref={responseRef} className="mt-8">
                  <ResponsePanel
                    response={response}
                    query={query}
                    onSubmitFeedback={handleSubmitFeedback}
                    feedbackStatus={feedbackStatus}
                  />
                </div>
              )}
            </div>

            <DocumentUpload
              onUpload={handleFileUpload}
              onAnalysisReady={handleAnalysisReady}
              uploadedDocs={uploadedDocs}
              uploadProgress={uploadProgress}
            />
          </div>
        )}

        {activeTab === "history" && (
          <HistoryPanel history={history} onLoadEntry={loadFromHistory} onClear={clearHistory} />
        )}

        {activeTab === "settings" && <ModelSelector onLogout={handleLogout} />}
      </div>
    </div>
  );
}
